### ISSUE TITLE
Support for using Kotlin

### ISSUE THREAD

**Issue by FredrikFolkesson** [CircleCI-Public/maven-orb#19]
It would be great if this orb would support Kotlin.

I am trying to parallelize our Kotlin tests and hoped to use this orb and the parallel_test job.

It uses some hard coded commands that assumes that the language is java:
```
        circleci tests glob
        <<parameters.test_directory>>/<<parameters.parallel_it_pattern>> | \
          sed -e 's#^<<parameters.test_directory>>/\(.*\)\.java#\1#' | \
          tr "/" "." > .circleci/tests/failsafe_classnames
```

What I would like to do is something like this in my workflow:

```
      - maven/parallel_test:
          name: build-jar-and-test
          context: Build
          executor: executor-with-postgres-image
          parallelism: 2
          settings_file: .circleci/maven-settings.xml
          test_directory: src/test/kotlin
          parallel_test_pattern: '**/*Test*.kt'
          post-steps:
            - persist_to_workspace:
                root: ./target
                paths:
                  - service.jar
            - persist_to_workspace:
                root: ./docker
                paths:
                  - Dockerfile
``` 

I am currently getting this error:
```
Error reading historical timing data: file does not exist
Requested weighting by historical based timing, but they are not present. Falling back to weighting by name.

Exited with code exit status 1
CircleCI received exit code 1
```
