### ISSUE TITLE
Test patterns for parallel_test are incorrect

### ISSUE THREAD

**Issue by sivaprasadreddy** [CircleCI-Public/maven-orb#36]
**Orb Version**
1.4.0

**Describe the bug**
While trying to run tests parallelly the unit tests pattern for surefire is considering integration tests pattern (`*IT.java`) instead of (`*Test*.java`)

**To Reproduce**
Create a Java app with some unit tests with naming convention `*Test*.java` and some integration tests with naming `*IT.java` and run with following CircleCI config.

```
version: 2.1
orbs:
  maven: circleci/maven@1.4.0
workflows:
  build_and_test:
    jobs:
      - maven/parallel_test:
          command: "verify"
          parallelism: 4
```
