### ISSUE TITLE
Failed with Cache settings

### ISSUE THREAD

**Issue by hantsy** [CircleCI-Public/maven-orb#43]
My circle CI config is like the following:

```yaml
version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@3.2.5
executors:
  ubuntu:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true    # default - false
  docker-mongo:
    docker:
      - image: cimg/openjdk:17.0
      - image: mongo:latest
jobs:
  build:
    executor: ubuntu
    steps:
      - run:
          name: "Install JDK 17"
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            java -version
      - checkout      
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose -f ./docker-compose.yml up -d
      - maven/with_cache:
          steps:
            - run: mvn -q test verify -Pcoverage
      - maven/process_test_results
      - codecov/upload:
          when: on_success
workflows:
  build:
    jobs:
      - build
      # filters:
      #   branches:
      #     only:
      #       - master
```

it is failed on CirCle CI due to a cache issue.

```bash
#!/bin/bash -eo pipefail
#!/bin/bash
find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed

find: ‘./data/journal’: Permission denied

Exited with code exit status 1

CircleCI received exit code 1

```

Can I specify the cache key directly?
